spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mybatbu.cgrlepfqc0gc.ap-northeast-2.rds.amazonaws.com:3306/test
    username: admin
    password: dlcjf0409

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql

  jwt:
    secret: ENC(oAMu1VEToExZeXoxYLwhG5hXaC1pvv7WgbfCov4Yh7XvcXrbK4zU1kW0nEUZgm9EdJEYGXBSXYQ=)

  servlet:
    multipart:
      enabled: true
      max-file-size: 4MB
      max-request-size: 4MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

ncpms:
  baseUrl: http://ncpms.rda.go.kr/npmsAPI/service
  serviceKey: 2023d6e7b8a2c0598a9537e535c210f3d67a
